version: '2.4'

x-mastermind-environment:
  &default-mastermind-env
  - GLOBAL_SECRET_KEY=${GLOBAL_SECRET_KEY}
  - POSTGRESQL_HOST=waldur-db
  - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
  - REDIS_HOST=waldur-queue
  - REDIS_PASSWORD=${REDIS_PASSWORD}
  - GLOBAL_DEFAULT_FROM_EMAIL=${GLOBAL_DEFAULT_FROM_EMAIL}
  - SENTRY_DSN=${SENTRY_DSN}
  - GLOBAL_DEBUG=${GLOBAL_DEBUG}
  - KEYCLOAK_SECRET=${KEYCLOAK_SECRET}
  - SENTRY_ENVIRONMENT=${SENTRY_ENVIRONMENT}

x-mastermind-volumes:
  &default-mastermind-volumes
  - ${CONFIG_FOLDER}/waldur-mastermind/override.conf.py:/etc/waldur/override.conf.py
  - ${CONFIG_FOLDER}/waldur-mastermind/logging.conf.py:/etc/waldur/logging.conf.py
  - ${CONFIG_FOLDER}/waldur-mastermind/beat:/usr/local/bin/beat
  - ${CONFIG_FOLDER}/waldur-mastermind/worker:/usr/local/bin/worker
  - ${CONFIG_FOLDER}/waldur-mastermind/saml2.conf.py:/etc/waldur/saml2.conf.py
  - ${CONFIG_FOLDER}/waldur-mastermind/id_rsa:/etc/waldur/id_rsa
  - ${CONFIG_FOLDER}/waldur-mastermind/id_rsa.pub:/etc/waldur/id_rsa.pub
  - ${CONFIG_FOLDER}/waldur-mastermind/saml2/credentials:/etc/waldur/saml2/credentials
  - ${CONFIG_FOLDER}/waldur-mastermind/saml2/metadata:/etc/waldur/saml2/metadata
  - ${CONFIG_FOLDER}/waldur-mastermind/valimo:/etc/waldur/valimo
  - ${CONFIG_FOLDER}/waldur-mastermind/notification-templates.yaml:/etc/waldur/notification-templates.yaml
  - ${CONFIG_FOLDER}/waldur-mastermind/auth.yaml:/etc/waldur/auth.yaml
  - ${CONFIG_FOLDER}/waldur-mastermind/support.yaml:/etc/waldur/support.yaml
  - ${CONFIG_FOLDER}/waldur-mastermind/whitelabeling.yaml:/etc/waldur/whitelabeling.yaml
  - ${CONFIG_FOLDER}/whitelabeling:/etc/waldur/icons
  - ${LIB_FOLDER}:/var/lib/waldur
  - /var/run/docker.sock:/var/run/docker.sock
  - /opt/waldur-script-launchzone:/opt/waldur-script-launchzone

x-mastermind-hosts:
  &default-mastermind-hosts
  - ${EXTRA_HOST}

services:
  # PostgreSQL
  waldur-db:
    container_name: waldur-db
    image: '${DOCKER_REGISTRY_PREFIX}library/postgres:16'
    user: root
    environment:
      - POSTGRES_USER=waldur
      - POSTGRES_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRES_DB=waldur
    volumes:
      - "./pgsql:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U waldur"]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: always

  # Redis
  waldur-queue:
    container_name: waldur-queue
    image: '${DOCKER_REGISTRY_PREFIX}bitnami/redis:latest'
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    restart: always

  # DB migration
  waldur-mastermind-db-migration:
    container_name: waldur-mastermind-db-migration
    image: '${DOCKER_REGISTRY_PREFIX}opennode/waldur-mastermind:${WALDUR_MASTERMIND_IMAGE_TAG}'
    environment: *default-mastermind-env
    volumes: *default-mastermind-volumes
    depends_on:
      waldur-db:
        condition: service_healthy
      waldur-queue:
        condition: service_started
    command: initdb

  # Whitelabeling initialization
  waldur-mastermind-whitelabeling-init:
    container_name: waldur-mastermind-whitelabeling-init
    image: '${DOCKER_REGISTRY_PREFIX}opennode/waldur-mastermind:${WALDUR_MASTERMIND_IMAGE_TAG}'
    environment: *default-mastermind-env
    volumes: *default-mastermind-volumes
    depends_on:
      waldur-db:
        condition: service_healthy
    command: init-whitelabeling

  # Celery
  waldur-mastermind-worker:
    container_name: waldur-mastermind-worker
    image: '${DOCKER_REGISTRY_PREFIX}opennode/waldur-mastermind:${WALDUR_MASTERMIND_IMAGE_TAG}'
    environment: *default-mastermind-env
    volumes: *default-mastermind-volumes
    depends_on:
      waldur-db:
        condition: service_healthy
      waldur-queue:
        condition: service_started
    healthcheck:
      test: ["CMD-SHELL", "celery -A waldur_core.server inspect ping"]
      interval: 30s
      timeout: 30s
      retries: 3
    command: worker
    restart: always
    extra_hosts: *default-mastermind-hosts

  # Celery-beat
  waldur-mastermind-beat:
    container_name: waldur-mastermind-beat
    image: '${DOCKER_REGISTRY_PREFIX}opennode/waldur-mastermind:${WALDUR_MASTERMIND_IMAGE_TAG}'
    environment: *default-mastermind-env
    volumes: *default-mastermind-volumes
    depends_on:
      waldur-db:
        condition: service_healthy
      waldur-mastermind-worker:
        condition: service_started
    command: beat
    restart: always
    extra_hosts: *default-mastermind-hosts

  # MasterMind API
  waldur-mastermind-api:
    container_name: waldur-mastermind-api
    image: '${DOCKER_REGISTRY_PREFIX}opennode/waldur-mastermind:${WALDUR_MASTERMIND_IMAGE_TAG}'
    environment: *default-mastermind-env
    volumes: *default-mastermind-volumes
    depends_on:
      waldur-mastermind-worker:
        condition: service_started
      waldur-mastermind-beat:
        condition: service_started
      waldur-db:
        condition: service_healthy
      waldur-queue:
        condition: service_started
    command: mastermind
    restart: always
    extra_hosts: *default-mastermind-hosts

  # HomePort
  waldur-homeport:
    container_name: waldur-homeport
    image: '${DOCKER_REGISTRY_PREFIX}opennode/waldur-homeport:${WALDUR_HOMEPORT_IMAGE_TAG}'
    environment:
      - API_URL=https://${WALDUR_DOMAIN:-localhost}/
      - TITLE=${WALDUR_TITLE:-"Waldur | Cloud Service Management"}
    volumes:
      - ${CONFIG_FOLDER}/waldur-homeport/config.template.json:/usr/share/nginx/config.template.json
      - ${CONFIG_FOLDER}/waldur-homeport/opt/waldur-homeport:/opt/waldur-homeport
    depends_on:
      waldur-db:
        condition: service_healthy
      waldur-mastermind-api:
        condition: service_started
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail http://waldur-homeport/ || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: always


  # HTTP Router
  caddy-router:
    container_name: caddy
    image: '${DOCKER_REGISTRY_PREFIX}library/caddy:2'
    ports:
      - '${WALDUR_HTTP_PORT:-80}:80'
      - '${WALDUR_HTTPS_PORT:-443}:443'
    environment:
      - VIRTUAL_HOST=${WALDUR_DOMAIN:-localhost}
      - TLS=${TLS:-"certs@waldur.com"}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./config/caddy-includes/:/etc/caddy-includes
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      waldur-homeport:
        condition: service_healthy
    restart: always

  keycloak:
    container_name: keycloak
    image: 'quay.io/keycloak/keycloak:25.0'
    restart: always
    environment:
      - KC_DB=postgres
      - KC_DB_URL_HOST=keycloak-db
      - KC_DB_URL_DATABASE=keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=${KEYCLOAK_POSTGRESQL_PASSWORD}
      - KC_PROXY=edge
      - KC_HOSTNAME_STRICT_HTTPS=false
      - KC_HOSTNAME_STRICT=false
      - KC_HTTP_ENABLED=true
      - KC_HTTP_RELATIVE_PATH=/auth
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
    volumes:
      - ./config/keycloak/realm.json:/opt/keycloak/data/import/realm.json
      - ./libraries/waldur-keycloak-mapper-1.1.2.jar:/opt/keycloak/providers/waldur-keycloak-mapper-1.1.2.jar:ro
    depends_on:
      - keycloak-db
    command: start --import-realm

  # PostgreSQL
  keycloak-db:
    container_name: keycloak-db
    image: '${DOCKER_REGISTRY_PREFIX}library/postgres:16'
    user: root
    environment:
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=${KEYCLOAK_POSTGRESQL_PASSWORD}
      - POSTGRES_DB=keycloak
    volumes:
      - keycloak_db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak"]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: always

  logger:
    image: umputun/docker-logger
    container_name: "logger"
    hostname: "logger"
    restart: always
    logging:
      driver: json-file
      options:
          max-size: "10m"
          max-file: "5"
    environment:
        - LOG_FILES=true
        - LOG_SYSLOG=false
        - MAX_FILES=10
        - MAX_SIZE=50
        - MAX_AGE=365
        - MIX_ERR=true
        - DEBUG=false
        - INCLUDE=waldur-db,waldur-queue,waldur-mastermind-db-migration,waldur-mastermind-worker,waldur-mastermind-beat,waldur-mastermind-api,waldur-homeport,caddy,keycloak
    volumes:
        - ${LOG_FOLDER}:/srv/logs
        - /var/run/docker.sock:/var/run/docker.sock

volumes:
  caddy_data:
  caddy_config:
  keycloak_db:

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: ${MTU:-1500}
