# General whitelabeling settings
site_name: "Waldur"
site_address: "changeme st 27"
site_email: "changeme@example.com"
site_phone: "+372changeme"
short_page_title: "changeme"
full_page_title: "Waldur | Cloud Service Management"
brand_color: "#307300"
brand_label_color: ""
hero_link_label: "changeme"
hero_link_url: "http://example.com"
site_description: "changeme"
currency_name: "EUR"
docs_url: "https://docs.waldur.com/"
support_portal_url: "https://docs.waldur.com/"
# The absolute path to the logo file in the container
# Format: /etc/waldur/icons/<filename from the config/whitelabeling folder>
powered_by_logo: ""
hero_image: ""
sidebar_logo: ""
sidebar_logo_mobile: ""
site_logo: ""
login_logo: "/etc/waldur/icons/login_logo.png"
favicon: "/etc/waldur/icons/favicon.ico"
